language: python
python:
# - '2.6'
- '2.7'
# - '3.3'
# - '3.4'
# - '3.5'
# - 3.5-dev
# - '3.6'
# - 3.6-dev
# - 3.7-dev
install: 
script:
- echo "we good"
deploy:
  matrix:
  - provider: pypi
    twine_version: 1.12.1
    user: teradactol
    password:
      secure: cLeOcxqyPVyUQY4dcdK1ydGeQhPYaa4UYfEcINlTIySry+D/VFSmA8Dt7mMbiqq4jExBzsrmVEl6cc0DWh+ZQp755rUtexWjZis/one6s8rC4lbKxTRiaJGBj7ocFglQNEiq35uEgHr+rE91MlAhN0RCTK2MC4+iHAH/gYYH+DcKEPfYz7ep8z1mKYXxtRlbSVjLjdqAQ0esatpErOzIDSekR8n8f+Zex8aC8aTOOd9CK6u3DLgW/yv4IT+QHZzTNBW0vO19tCAp8pkL5iCdPJYPt/eDwz3hoFDEUkGsrOSBxYkBXfcH60fxKc27UtX4JRH7Kle/GZtpEVxaTycZElMDOahFY3fHAKfFKqwzaWTDCpurgy0u2P6hgEFJm6P+EGeVPA3cfQUe3xZN1KgpAaT6dYJGtK728UwEEuWb/y0kCl2uIWCMCjhRPxk+RYk3Ik6ldioXAK9znJpZduIetQ2yaVMo4wIS+K0XyoiMrr3zQQoSlrfEuHennBAMTskr10Z7911dHW0nh1mTOYM9fpfarjOh27RSx/N6NVZpCMPAxArqdSXWl66O7sOqZOvJW5kBYNvX6ObOROXEeVu43G/d/FDK9iC9g9LZljllWuHsruxUYu+cE1XSNS+82QJkj4w434IwZrSKGwZP2xxH7kSJQ6dKslu5iEQdWONUGMI=
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      python: 2.7
      branch: test-release
  - provider: pypi
    twine_version: 1.12.1
    user: teradactol
    password:
      secure: cLeOcxqyPVyUQY4dcdK1ydGeQhPYaa4UYfEcINlTIySry+D/VFSmA8Dt7mMbiqq4jExBzsrmVEl6cc0DWh+ZQp755rUtexWjZis/one6s8rC4lbKxTRiaJGBj7ocFglQNEiq35uEgHr+rE91MlAhN0RCTK2MC4+iHAH/gYYH+DcKEPfYz7ep8z1mKYXxtRlbSVjLjdqAQ0esatpErOzIDSekR8n8f+Zex8aC8aTOOd9CK6u3DLgW/yv4IT+QHZzTNBW0vO19tCAp8pkL5iCdPJYPt/eDwz3hoFDEUkGsrOSBxYkBXfcH60fxKc27UtX4JRH7Kle/GZtpEVxaTycZElMDOahFY3fHAKfFKqwzaWTDCpurgy0u2P6hgEFJm6P+EGeVPA3cfQUe3xZN1KgpAaT6dYJGtK728UwEEuWb/y0kCl2uIWCMCjhRPxk+RYk3Ik6ldioXAK9znJpZduIetQ2yaVMo4wIS+K0XyoiMrr3zQQoSlrfEuHennBAMTskr10Z7911dHW0nh1mTOYM9fpfarjOh27RSx/N6NVZpCMPAxArqdSXWl66O7sOqZOvJW5kBYNvX6ObOROXEeVu43G/d/FDK9iC9g9LZljllWuHsruxUYu+cE1XSNS+82QJkj4w434IwZrSKGwZP2xxH7kSJQ6dKslu5iEQdWONUGMI=
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      python: 2.7
      branch: release    