language: python
python:
# - '2.6'
- '2.7'
# - '3.3'
# - '3.4'
# - '3.5'
# - 3.5-dev
# - '3.6'
# - 3.6-dev
# - 3.7-dev
install: 
script:
- echo "we good"
deploy:
  - provider: pypi
    twine_version: 1.12.1
    user: teradactol
    password:
      secure: "qusYQD7eq7NZ1tXCy1A9Ht1xDUXUXN4xbvv2WbNhv2jR9/C8LqMcy3LPvJqNGVFApsGR+N7waTuqmzfiMFaYNZcIxA3cZymYNBQMDFr/O901QfcxQT1vPlT0cZYOKoJvy2iwH+LibwnUfjh1gKIZZUvSdEh1h6gMi+zzrgJi8oiR3p8TYAZdppOm5KYTUO8VxjmB8QpR5Adi4RggpNpNaxNO8RLhUY+enOJBa4b211Ccv/xTcL2+FFen1vzUnNvxkvwAq3xOqrp0wK1IrD91TJRMaCdEYpAY7oUA38SX2mBl6ukLebuzgMCxde8hEWsSFF64UMWh1dMJUdwN2p1mc/U9TOQ1iRg+CSjjetmDpQjbfk+vODqQJLpNPNNKbLxBeobjdGTYYnYYPiRUbBtECp40kvuFe8iww/58OV57Q8aJh6KIn5erDLQPkFbxwAAYpnH6+O9od1EbINf8sH5wtmv38PKUtZ1ifKH5MbCHeZ3uMvaeQ0jXH6rhgO7SMK6sJRdbvXlFWHrYFUhXiT6Hp4RsYeG5WO7MN110YWEzBxBUkQVdEdrniFs5o9pBwWDQGTrt3tBZe3r49DUNGip7MQAiBA8og3CDh7PIvfB/g06jjSR4V0G6wvDgJjEgJGGUtaa1VNlUjL8lhpPNc3ZAZYvg6vTzserlgeRP2WHICQ8="    
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      python: 2.7
      branch: test-release
  - provider: pypi
    twine_version: 1.12.1
    user: teradactol
    password:
      secure: "qusYQD7eq7NZ1tXCy1A9Ht1xDUXUXN4xbvv2WbNhv2jR9/C8LqMcy3LPvJqNGVFApsGR+N7waTuqmzfiMFaYNZcIxA3cZymYNBQMDFr/O901QfcxQT1vPlT0cZYOKoJvy2iwH+LibwnUfjh1gKIZZUvSdEh1h6gMi+zzrgJi8oiR3p8TYAZdppOm5KYTUO8VxjmB8QpR5Adi4RggpNpNaxNO8RLhUY+enOJBa4b211Ccv/xTcL2+FFen1vzUnNvxkvwAq3xOqrp0wK1IrD91TJRMaCdEYpAY7oUA38SX2mBl6ukLebuzgMCxde8hEWsSFF64UMWh1dMJUdwN2p1mc/U9TOQ1iRg+CSjjetmDpQjbfk+vODqQJLpNPNNKbLxBeobjdGTYYnYYPiRUbBtECp40kvuFe8iww/58OV57Q8aJh6KIn5erDLQPkFbxwAAYpnH6+O9od1EbINf8sH5wtmv38PKUtZ1ifKH5MbCHeZ3uMvaeQ0jXH6rhgO7SMK6sJRdbvXlFWHrYFUhXiT6Hp4RsYeG5WO7MN110YWEzBxBUkQVdEdrniFs5o9pBwWDQGTrt3tBZe3r49DUNGip7MQAiBA8og3CDh7PIvfB/g06jjSR4V0G6wvDgJjEgJGGUtaa1VNlUjL8lhpPNc3ZAZYvg6vTzserlgeRP2WHICQ8="    
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      python: 2.7
      branch: release    